import Link from 'next/link';
import NaiveCompare from '../../components/NaiveCompare';
import { readCompareDocument } from '../../src/store/compare';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Greenlight — a guardrailed check against a bare model',
};

export default function ComparePage() {
  const doc = readCompareDocument();

  if (!doc) {
    return (
      <main className="mx-auto max-w-[820px] px-6 py-20">
        <h1 className="text-lg text-slate-100">No comparison has been captured.</h1>
        <p className="mt-2 max-w-[70ch] text-[13px] leading-relaxed text-slate-400">
          Run <code className="font-mono text-slate-300">npm run compare:capture</code> to record a
          real model response and rebuild this page from it.
        </p>
        <Link href="/" className="mt-6 inline-block text-sm text-sky-300 hover:text-sky-200">
          Back to scanning
        </Link>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-[1500px] px-6 py-10">
      <div className="max-w-[70ch]">
        <h1 className="text-[32px] font-semibold leading-[1.15] tracking-tight text-slate-50">
          Ask a model about YouTube policy and it answers from memory.
        </h1>
        <p className="mt-3 text-[17px] leading-relaxed text-slate-400">
          The most repeated monetization advice on the internet — never swear in the first seven
          seconds — was deleted in July 2025. It is still in every blog post, every tips video, and
          most training data. Below is the same clip through a bare model and through Greenlight.
        </p>
        <p className="mt-3 text-[13px] leading-relaxed text-slate-500">
          Both columns are generated by{' '}
          <code className="font-mono text-slate-400">scripts/make-naive-compare.ts</code> and
          committed as static JSON. This page makes no API calls.
          {doc.capturedAt ? ` Captured ${new Date(doc.capturedAt).toISOString().slice(0, 10)}.` : ''}
        </p>
      </div>

      <div className="mt-8">
        <NaiveCompare doc={doc} />
      </div>

      <p className="mt-8 max-w-[80ch] text-[13px] leading-relaxed text-slate-500">
        This is not an argument that models are useless — Greenlight uses one too. It is an argument
        about where the policy comes from. A model asked to recall a rule will produce a fluent,
        confident, undated, uncitable answer. A model handed the current clause text and allowed to
        cite nothing else will produce an answer you can check in one click.
      </p>

      <Link
        href="/"
        className="mt-8 inline-block text-sm text-sky-300 hover:text-sky-200"
      >
        Scan a file
      </Link>
    </main>
  );
}
